import { ConnectWallet, useAddress, useLogin } from "@thirdweb-dev/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const address = useAddress();
  const login = useLogin();

  return (
  <>
      <Head>
        <title>Mirac.eth App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.container}>
      <h1>Unlock Your Journey! Connect Your Wallet to Step Inside the App 🚀</h1>
      <ConnectWallet className="my-custom-class"/>
      <div class="footer"><a target="_blank" href="https://bio.link/099" rel="noreferrer"><Image src="/mail.png" height={22} width={20} alt="contact"/></a>
Developed by Mirac.eth</div>
    </div>
    </>
  );
}
